.travis.yml, kernprof.py, line_profiler.py
Original discussion is in https://github.com/rkern/line_profiler/pull/153
=> Fix pep 479

CHANGELOG.rst, README.rst, line_profiler/__init__.py, line_profiler/__main__.py, line_profiler/line_profiler.py
Fixes (https://github.com/rkern/line_profiler/issues/176) in the original repo.
=> Fix main file

.coveragerc, .gitignore, .travis.yml, CHANGELOG.rst, clean.sh, line_profiler/__init__.py, line_profiler/line_profiler.py, requirements/tests.txt, run_tests.py, setup.py, tests/test_cli.py
Check to ensure that the command line scripts work as advertised. 
I'm also using the PR to add code reporting of code coverage.  
Fixes #9
=> Add test for command line usage

CHANGELOG.rst, kernprof.py, line_profiler/line_profiler.py
Closes #22 and closes #23 
I'm open to suggestions for a better help message for `--unit` :smile:
=> Add cli arg for output unit and skip (strip) zero

.circleci/config.yml, .github/workflows/python-package.yml, .github/workflows/python-publish.yml, line_profiler/__init__.py, line_profiler/line_profiler.py, publish.sh, requirements/runtime.txt, run_manylinux_build.sh, setup.py
Adding github actions as a potentially more secure way to do automated pypi publishing (wrt to CircleCI).
=> Add Github Actions

.github/workflows/python-publish.yml, .github/workflows/python-test.yml, README.rst
Renamed actions workflows and added badges to the README
=> Add actions badges

.circleci/config.yml, .github/workflows/python-test.yml
Getting coverage to register on codecov.io
=> Fix codecov call

setup.py
=> Removed old C-ext logic

CHANGELOG.rst, MANIFEST.in, kernprof.py, line_profiler/line_profiler.py
Forgot to include the actual c sources in sdist
=> Include c source files in manifest

requirements/runtime.txt
=> Fix ipython version requirements for python 3.6

CHANGELOG.rst, kernprof.py, line_profiler/line_profiler.py
Forgot to add a CHANGELOG note in #93
=> Add CHANGELOG note related to #93

line_profiler/line_profiler.py
Now support Xeus-python
https://github.com/jupyter-xeus/xeus-python
This update should also fully solve issue #101
=> Allow the profiler to work with xeus-python

README.rst
fixed spelling of "alternatively"
=> fixed typo in README.rst

README.rst
Adds notes to README about modern viewing tools based on discussion in https://github.com/pyutils/line_profiler/issues/55
=> Add notes about GUIs in README

CHANGELOG.rst, kernprof.py
Fixes #109 
Alternative to #110
I followed @Erotemic suggestion to use the ``stream`` optional argument to write to the original ``sys.stdout``.
=> Output stream

CHANGELOG.rst, kernprof.py, line_profiler/line_profiler.py
Rebased version of https://github.com/pyutils/line_profiler/pull/136/
=> Fix coroutines

README.rst
@Erotemic, Add new tool in a list of 3rd party tools - ``pprof``.
Source Code: https://github.com/mirecl/pprof
PyPi: https://pypi.org/project/pprof/
**Example report:**
See more in #131
=> 🌐 Add 3rd party tools - pprof

CHANGELOG.rst, clean.sh, setup.py
Add ability to bypass the dependency on cmake / scikit-build.
=> Add alternative build method that avoids cmake / scikit-build

README.rst
No-nonsense terse instructions that say how to use `line_profiler`. In response to #174 .
=> Add Quick Start to README

line_profiler/_line_profiler.pyx
Fix #210. The correct numbers were being collected, but there was an issue when displaying them.
=> Fix hit counts on branches being messed up

README.rst, requirements/ipython.txt, requirements/tests.txt, setup.py
=> Re-add ipython req support and update readme

CHANGELOG.rst, pyproject.toml, requirements/build.txt
Investigates supporting ARM wheels on OSX. 
Fixes: https://github.com/pyutils/line_profiler/issues/250
=> Add arm support for osx

CHANGELOG.rst, line_profiler/_line_profiler.pyx
Fixes https://github.com/pyutils/line_profiler/issues/284
=> Fix noop code
