.travis.yml
Use the production version instead of the prerelease version.
=> Travis CI: Upgrade to Python 3.8.0

requirements/tests.txt
(Please squash this PR) This should fix every PR that fails on 3.5 due to a bad version of pytest installed.
=> Update pytest and pytest-cov in requirements to fix travis tests

CHANGELOG.rst, README.rst, line_profiler/line_profiler.py
In the recent merge of #31 I forgot to add a CHANGELOG and update the `__version__`.
=> Bump versions and add CHANGELOG for recent merge

kernprof.py, line_profiler/line_profiler.py
Update to argparse because it's better (code, error handling, help, etc), I also changed some help messages and changed the shorthand for `--skip-zero` to `-z` (was `-s` in line_profiler) to be compatible with kernprof.
For comparison, before:
```
> python -m line_profiler
Usage: python -m line_profiler profile.lprof
__main__.py: error: Must provide a filename.
```
```
> python -m line_profiler -h
Usage: python -m line_profiler profile.lprof
Options:
--version             show program's version number and exit
-h, --help            show this help message and exit
-u UNIT, --unit=UNIT  Output unit (in seconds) in which the timing info is
to be displayed. Defaults to 1e-6.
-s, --skip-zero       Hide functions which have not been called.
```
```
> kernprof -h
Usage: kernprof [-s setupfile] …
```
=> Update to argparse, improve cli help

README.rst
Thank you for the project!
I spent a lot of time looking to find out visualizers are hard to come by! Hopefully this can help readers
1. Removes RunSnakeRun (won't run on most systems, not python 3 compatible either, [1](https://stackoverflow.com/a/33121014), [2](https://stackoverflow.com/questions/49790608/runsnakerun-does-not-open-at-all-on-windows))
2. Adds [SnakeViz](https://github.com/jiffyclub/snakeviz/) (which is maintained)
3. Moves visualizers directly compatible with output to the front
4. Easier to read that KCacheGrind and related tools require an extra conversion step
=> README: Remove RunSnakeRun (unmaintained)

CHANGELOG.rst, README.rst, kernprof.py, line_profiler/line_profiler.py, tests/test_cli.py
Attempting to fix issues in 3.2.x 
* ENH: Added better error message when c-extension is not compiled.
* FIX: Kernprof no longer imports line_profiler to avoid side effects.
=> Branch for 3.2.2

kernprof.py
This:
kernprof -v profile_me.py
Produces this trace back
Wrote profile results to profile_me.py.prof
Traceback (most recent call last):
File ".../bin/kernprof", line 11, in <module>
sys.exit(main())
File "...site-packages/kernprof.py", line 243, in main
prof.print_stats(output_unit=options.unit, stripzeros=options.skip_zero)
TypeError: print_stats() got an unexpected keyword argument 'output_unit'
While:
kernprof -v -l profile_me.py
works because the profiler is an instance of a different class.
This patch fixes this problem.
=> Fix command line option `-v` if used without `-l`

line_profiler/line_profiler.py
Profiling in Jupyter Notebooks or Jupyter Lab with recent ipykernel
versions (>= 6), resulted in the following error message:
Could not find file /tmp/ipykernel_8298/3242911465.py
Are you sure you are running this program from the same
directory that you ran the profiler from?
Continuing without the function's contents.
The timing output then does not include source code lines.
The problem is that line_profiler tries to determine when it runs in
side IPython/Jupyter using a simple heuristic based on the reported
filename. New ipykernel versions changed this filename pattern and broke
our test.
As a quick fix, amend the test so it continues working. Longer term, a
more robust solution would be desirable.
Fixes pyutils/line_profiler#86
=> Fix missing source in Jupyter notebook/lab

.github/workflows/tests.yml
The pypa repo seems like it is more official, so I'm opting to point there, even though it does look like joerick is the lead maintainer.
=> Switch joerick to pypa base for cibuildwheel

.codecov.yml, CHANGELOG.rst, kernprof.py, line_profiler/line_profiler.py, requirements/tests.txt
Bumps `__version__` to '3.5.0' and adds a codecov config.
=> Stub out version 3.5

line_profiler/line_profiler.py
Profiler crashes in case when linenos is an empty list
'ValueError: max() arg is an empty sequence'
Let's add an extra check for linenos before passing it to a max-function
=> Fix 'ValueError' upon empty linenos variable

CHANGELOG.rst, line_profiler/line_profiler.py
Fixes #100.
Here is a proposition to fix a rare case of ZeroDivisionError in case of empty function. I choose to display no percent value to have a clean output and not displaying wrong values, but it can of course be changed.
This is the result:
```
Total time: 0 s
File: example/profiling_test_script.py
Function: fast at line 59
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
59                                           @profile
60                                           def fast():
61         1          0.0      0.0               pass
```
I did not add tests specifically for this, since the total time at zero is non consistent. I can add a specific test calling ``show_func`` directly if needed.
I still have …
=> Avoid ZeroDivisionError in rare cases

CHANGELOG.rst, README.rst, line_profiler/__init__.py, line_profiler/ipython_extension.py, line_profiler/line_profiler.py, requirements.txt, requirements/ipython.txt, requirements/runtime.txt, requirements/tests.txt, setup.py, tests/test_ipython.py
The only runtime dependency is IPython, which needs many other libraries as well. This make a heavy installation for a features that is completely optional.
It was raised before in https://github.com/rkern/line_profiler/issues/112, with some PR that were never merged, apparently due to lack of time: https://github.com/rkern/line_profiler/pull/139, https://github.com/rkern/line_profiler/pull/114. There is also comments from @rkern that it should be optional: https://github.com/rkern/line_profiler/pull/90
This PR is my take on the subject, since I don't use ipython I had the motivation to get rid of it. It is still an optional dependency for pip, to be able to check the version: ``pip isntall line_profiler[ipython]``
I think that the approach in …
=> Make IPython optional

line_profiler/line_profiler.py
Currently `line_profiler` does not work on Windows + Jupyter Notebook due to filename test error. This pull request replaces the fixed `/` with `os.path.join` in the `is_ipython_kernel_cell(filename)`.
=> fix filepath test in is_ipython_kernel_cell for Windows

CHANGELOG.rst, line_profiler/_line_profiler.pyx, tests/test_line_profiler.py
Using `LineProfiler().add_function(decorated_func)` on a decorated function will trace the decorator and not the decorated function. A warning that is raised in the presence of a `__wrapped__` attribute might go a long way in helping users with this edge case already. The `__wrapped__` attribute may be present if [`lru_cache` or `wraps` from `functools`](https://docs.python.org/3/library/functools.html?highlight=__wrapped__) are used. 
See #167.
=> Warn when adding functions with a __wrapped__ attribute

CHANGELOG.rst, README.rst, kernprof.py, line_profiler/line_profiler.py, pyproject.toml, requirements/build.txt
Fixes: #204.  See #205 for an alternate fix, which I don't prefer.
=> Stop requiring a bleeding-edge Cython.

CHANGELOG.rst, kernprof.py, line_profiler/line_profiler.py, requirements/tests.txt
I added some logic in `show_func` to widen columns if necessary. I also added an associated doctest that demonstrates the issue.
Before when hits or time was large enough it would overflow the column and make the lines have bad indentation:
```python
Total time: 1.32e+11 s
File: /home/joncrall/code/line_profiler/line_profiler/line_profiler.py
Function: show_text at line 306
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
306                                           def show_text(stats, unit, output_unit=None, stream=None, stripzeros=False):
307                                               """ Show text for the given timings.
308                                               """
309 100000000.0 2000000000.0 …
```
=> Fix text alignment for wide columns in show_func 

CHANGELOG.rst, line_profiler/line_profiler.py, tests/complex_example.py, tests/test_complex_case.py, tests/test_line_profiler.py
Use scientific notation when columns get too long. This should prevent columns from becoming misaligned in the output stats.
Adds several new tests for this and other potential issues.
=> Column Fixes

CHANGELOG.rst, line_profiler/line_profiler.py, requirements/optional.txt
Factored the rich output features out of https://github.com/pyutils/line_profiler/pull/222 into its own PR.
Adds several options to `show_text` to control:
* if the per-function output is sorted by ascending total time
* if a summary of the per-function total time is shown at the end
* if we attempt to use rich to highlight the CLI output.
These options can also be controlled from the CLI using new arguments:
```python
parser.add_argument(
'-r',
'--rich',
action='store_true',
help='Use rich formatting',
)
parser.add_argument(
'-t',
'--sort',
action='store_true',
help='Sort by ascending total time',
)
parser.add_argument(
'-m',
'--summarize',
action='store_true',
help='Print a summary of total function time',
)
```
The output is pretty:
This builds on an older PR: …
=> Rich output

CHANGELOG.rst, docs/make.bat, docs/source/conf.py, docs/source/index.rst, docs/source/kernprof.rst, docs/source/line_profiler.__main__.rst, docs/source/line_profiler._line_profiler.rst, docs/source/line_profiler.explicit_profiler.rst, docs/source/line_profiler.ipython_extension.rst, docs/source/line_profiler.line_profiler.rst, docs/source/line_profiler.rst, docs/source/modules.rst, kernprof.py, line_profiler/__init__.py, line_profiler/explicit_profiler.py, line_profiler/explicit_profiler.pyi, tests/test_explicit_profile.py
@Theelx @Mogost @rkern and others: Looking for feedback on a proposed new feature.
With this new change users will be able to:  `from line_profiler import profile` and then run with `LINE_PROFILE=1` and line-profiler will dump profile information to stdout and disk at the end of execution. 
When it comes to imports, I prefer explicit ones. I think the current primary way to use line profiler is confusing and I think it would be an enhancment if there was an alternative way to use line profiler where you just import it and use it.
I've been doing this for years in my xdev module: https://github.com/Erotemic/xdev/blob/main/xdev/profiler.py
The above code is overcomplicated, but the resulting feature is something I use often. I've ported a much simpler version to this PR, and I'm looking for …
=> FEAT: Explicit top-level `profile` decorator.

README.rst, docs/source/conf.py, kernprof.py, line_profiler/__init__.py, line_profiler/_line_profiler.pyx, line_profiler/explicit_profiler.py, line_profiler/ipython_extension.py, line_profiler/line_profiler.py, requirements/tests.txt, tests/complex_example.py, tests/test_complex_case.py, tests/test_explicit_profile.py, tests/test_import.py
Adding support for readthedocs
=> ReadTheDocs

CHANGELOG.rst, clean.sh, line_profiler/_line_profiler.pyx, line_profiler/autoprofile/ast_profle_transformer.py, line_profiler/explicit_profiler.py, line_profiler/line_profiler.py, tests/complex_example.py, tests/test_autoprofile.py, tests/test_complex_case.py, tests/test_duplicate_functions.py, tests/test_explicit_profile.py
Attempts to fix: https://github.com/pyutils/line_profiler/issues/232
Adds in tests and also contains other code cleanup.
=> Patch for duplicate functions

requirements/optional.txt, requirements/tests.txt, tests/test_ipython.py
Should speedup the build part of the CI by only running the basic tests in cibuildwheel. The optional tests are handled later actions.
=> Dont require ipython for at cibuildwheel test time

line_profiler/_line_profiler.pyx
For each call of `get_stats`, the implicit conversion of the C++ `unordered_mapping` `c_code_map` to a Python dict is currently being performed `len(code_hash_map)` -times. In scenarios where a large amount of code is being profiled, this can result in a significant performance penalty.
Moving the implicit conversion out of the loop and only performing it once is what this PR proposes.
In our use case, line-profiler 4.x has been unusable due to this performance hit (which I've only just quantified and narrowed down to this conversion today):
With `len(code_hash_map)` at around 1000, line_profiler main branch shows for me:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
2    2.043    1.021    2.044    1.022 _line_profiler.pyx:358(get_stats)
```
And with this PR: …
=> get_stats: Avoid dict conversion of c_code_map for each element of code_hash_map

line_profiler/timers.c
So I had a problem running the `line_profiler` on a RPI - 32bit system.
Whenever I tried to profile a function that exceeds some time limit, the `line_profiler` report show negative values for time measuring variables.
I believe I have experienced this kind of behavior due to overflow.
Showcase:
`foo.py`:
Simulation of `foo.py` **before** the changes I represent in this PR:
Simulation of `foo.py` **after** the changes I represent in this PR:
=> Support 32bit system

.github/workflows/tests.yml, .readthedocs.yml, CHANGELOG.rst, docs/source/conf.py, kernprof.py, line_profiler/__init__.py, line_profiler/_line_profiler.pyx, line_profiler/line_profiler.py, pyproject.toml, requirements/build.txt, requirements/tests.txt, setup.py, tests/test_explicit_profile.py, tests/test_ipython.py
Updating CI to test Python 3.12
=> Support 3.12

tests/test_complex_case.py
If tests are executed outside a virtualenv "python" might not be the python interpreter the tests are being invoked with
=> Invoke subshell with the current python interpreter

README.rst
This updates the README to include modern (imo easier) instructions for running line profiler.
=> Add modern quickstart instructions to README

CHANGELOG.rst, line_profiler/line_profiler.py, tests/test_line_profiler.py
In the latest version the "summarize" part of `line_profiler.line_profiler.show_text` will display the duration of all decorated functions even if stripzeros is True and the total time is zero. This PR patches that so now only the non-zero durations will print when this is true.
=> Respect stripzeros in summary report

.github/workflows/tests.yml
Have cibuildwheel run on macOS-latest and macos-13 for x86 and arm64 wheel variants.
=> Ensure x86 and arm64 wheels are built for osx

line_profiler/line_profiler.py
Rebased version of https://github.com/pyutils/line_profiler/pull/261
=> Rebased normpath comparison

line_profiler/autoprofile/util_static.py
(Closes issue #279)
Added support for annotated assignments in the static parser used by auto-profiling, so that type-annotated `__editable___*finder.py` scripts (as generated e.g. by `setuptools >= 70.0`) can be correctly handled
=> Added support for annotated assignments in the static parser

.github/workflows/tests.yml, CHANGELOG.rst, line_profiler/_line_profiler.pyx, line_profiler/autoprofile/autoprofile.py, line_profiler/line_profiler.py, pyproject.toml, run_tests.py, setup.py, tests/test_assumptions.py, tests/test_autoprofile.py, tests/test_explicit_profile.py
Working on updating CI and supporting 3.13
=> Support 313

.gitignore, docs/source/index.rst, docs/source/manual/examples/example_units.rst, docs/source/manual/examples/index.rst, line_profiler/__init__.py
Documentation to address question in https://github.com/pyutils/line_profiler/issues/291
Adds a manual examples page in the docs folder, with a new example for the above question. Also links to other examples already existing in the docs.
=> Add unit example

setup.py
Fixes #316.
Tested in python 3.14.0a4+ (commit `5c9a63f62c9e56d1576c2dc62c986f2be988729f`) and in python 3.8.20 (the latest patch of the earliest supported by line_profiler). I'm making a wild assumption that it therefore works fine in-between.
=> Updated StaticVisitor

CHANGELOG.rst, line_profiler/_line_profiler.pyx, tests/test_complex_case.py, tests/test_line_profiler.py
Background
----
This came up during the discussion around #326. Since Python 3.12, profiling tools (like `cProfile.Profile`) are supposed to register themselves with `sys.monitoring.use_tool_id(sys.monitoring.PROFILER_ID, ...)` when in use, and `sys.monitoring.free_tool_id(sys.monitoring.PROFILER_ID)` when done.
This seemed like a trivial addition, but doing so naïvely caused `tests/test_complex_case.py::test_varied_complex_invocations()` to fail, presumably due to complications from the test script's use of concurrency. Trying to debug it was difficult, particularly since the singular test was essentially 11 in a trenchcoat.
The PR
----
Hence, this (draft) PR: 
- Refactors `tests/test_complex_case.py::test_varied_complex_invocations()` into a parametrized test, which allows the 11 …
=> ENH: `sys.monitoring` compliance

CHANGELOG.rst, kernprof.py, line_profiler/line_profiler.py, line_profiler/line_profiler.pyi, line_profiler/profiler_mixin.py, line_profiler/profiler_mixin.pyi, tests/test_explicit_profile.py
Synopsis
----
When writing #323, we noticed that the one of the new tests are failing in Python 3.12 and above, and accidentally discovered that the `prof.runctx()` code path is currently untested. Said code path is executed when `kernprof` is run with neither the `-b`/`--builtin` nor `-l`/`--line-by-line` options. 
Further investigation revealed that the introduction of `sys.monitoring` and tooling registration is to blame, especially [these lines in `lsprof.c`](https://github.com/python/cpython/blob/c1e708ab070a08a4427e230dd9127138d527ceef/Modules/_lsprof.c#L757-761) of the Python source code, corresponding to `cProfile.Profile.enable()` – which causes `kernprof.ContextualProfile.enable_by_count()` to fail when first called, because the profiling tool `'cProfile'` has already been …
=> FIX: `kernprof` erroring out in non-`-l`, non-`-b` mode in Python 3.12+

CHANGELOG.rst, line_profiler/autoprofile/ast_profile_transformer.py, line_profiler/autoprofile/ast_profile_transformer.pyi, tests/test_autoprofile.py
Closes #330.
- `CHANGELOG.rst`:  
Added entry
- `line_profiler/autoprofile/ast_profile_transformer.py[i]::AstProfileTransformer.visit_AsyncFunctionDef()`:  
New method (shares the same implementation with `.visit_FunctionDef()`) so that the transformer knows to also decorate `async def` statements
- `tests/test_autoprofile.py::test_async_func_autoprofile()`:  
Test for auto-profiling of async functions (fails on main, passes wth this fix)
=> Fix: auto-profiling `async def`

CHANGELOG.rst, kernprof.py, line_profiler/autoprofile/ast_profile_transformer.py, line_profiler/autoprofile/autoprofile.py, line_profiler/autoprofile/autoprofile.pyi, line_profiler/autoprofile/run_module.py, line_profiler/autoprofile/run_module.pyi, tests/test_autoprofile.py, tests/test_explicit_profile.py, tests/test_kernprof.py
In issue #29, it was requested that support for running modules be added to `kernprof` via an `-m` flag. While it was noted that [*explicit* decoration with the `LINE_PROFILE=1` environment-variable switch](https://github.com/pyutils/line_profiler/issues/29#issuecomment-1692639599) can mitigate having to call `kernprof` off the command line, this does not cover the use-case of *auto-profiling* module execution, like how the existing invocation `kernprof -l -p... script.py` covers script execution.
This PR adds the requested (but see Caveats) functionality by:
- Adding the `-m`/~~`--module`~~ **EDIT 13 Apr: long-option form no longer supported** boolean flag to `kernprof.py::main()`
- ~~Convenience: when `-m` is passed without specifying `-p`/`--prof-mod`, it defaults to `-p …
=> ENH: auto-profile module execution

CHANGELOG.rst, line_profiler/line_profiler.py, line_profiler/line_profiler.pyi, line_profiler/profiler_mixin.py, line_profiler/profiler_mixin.pyi, tests/test_line_profiler.py
(Closes #328)
Synopsis
----
This PR:
- Fixes the known bug that explicit decoration/wrapping of class and static (and also bound) methods returns non-instances thereof, resulting in wrong argument bindings.
- Fixes the lack of handling for async generator functions.
- Extends `LineProfiler` so that it can reliably handle decorating the following:
- `property`, `functools.cached_property`
- `functools.partial`
- `functools.partialmethod`
- Adds tests for all of the above.
Motivation
----
- As noted in #328, decorating class and static methods with `LineProfiler` (and by extension `GlobalProfiler`) is currently bugged because the returned object is a regular `types.FunctionType`, which has different behaviors on `.__get__()` compared with the decorated objects.
- It is also noticed that we …
=> FIX: (+ENH?) fixed and extended dispatching for `LineProfiler.__call__()`

CHANGELOG.rst, kernprof.py, line_profiler/autoprofile/autoprofile.py, tests/test_kernprof.py
Motivation
----
`kernprof -m` as it is now fails to address edge cases where the executed module is expected to be found at `sys.modules['__main__']`. One such cases is for the `@enum.global_enum` decorator, which searches `sys.modules` for the module whither to insert the enum instances. This causes [use-cases like `kernprof -m calendar`](https://github.com/pyutils/line_profiler/pull/337#issuecomment-2837178985) to fail. Notably, [a similar failure pattern](https://github.com/python/cpython/issues/103935#issuecomment-1526102367) is seen with even Python `stdlib` modules.
Changes
----
The key point of failure lies with how `kernprof` uses `runpy.run_module()` without the optional `alter_sys` argument. Since it defaults to false, the executed module is not inserted into `sys.modules`, and …
=> FIX: `kernprof -m`: presence of the executed module as `sys.modules['__main__']`

CHANGELOG.rst, kernprof.py, line_profiler/autoprofile/autoprofile.py, tests/test_kernprof.py, tests/test_line_profiler.py
Just noticed that I made the same mistake in #323, #332, and #339, where `@contextlib.contextmanager` is used to wrap generator functions to construct context managers: the `yield` statement and the subsequent cleanup code wasn't wrapped in a `try`–`finally` block, so the cleanup is eschewed if any exception occurred inside the `with` block/decorated function.
This PR fixes the bug in three functions:
- `kernprof.py::_restore_list()` (used by `main()`)
- `line_profiler/autoprofile/autoprofile.py::run.<locals>.restore_dict()`
- `tests/test_line_profiler.py::check_timings()`
One test is added to verify that the old behavior is problematic and is fixed by the PR:
- `tests/test_kernprof.py::test_kernprof_sys_restoration()`
Sorry for any inconvenience caused.
=> FIX: fixed cleanup code in `@contextlib.contextmanager`

line_profiler/line_profiler.py, line_profiler/line_profiler.pyi
Currently, packages that generate Python code aren't easy to profile with the line_profiler, unless doing some contortions to adjust the file name to something that triggers line_profiler to look into the linecache instead of the file system. This PR slightly broadens the existing support for ipython to support more code generators.
=> [RFC] Broaden support for profiling generated code

CHANGELOG.rst, docs/source/manual/examples/example_kernprof.rst, docs/source/manual/examples/index.rst, kernprof.py, tests/test_autoprofile.py
This PR is inspired by #323, which added the `-m` option to `kernprof` so that one can profile the execution of modules and packages. Much like how `kernprof <script>` parallels `python <script>`, and `kernprof -m <module>` `python -m <module>`, there may be use-cases that call for similar parallels for:
- `python -c <code>` (running literal code), and
- `... | python -` or `python - <<<"..."` (running code from `stdin`).
Hence this PR which adds to `kernprof`:
- Support for the special option `-c` (like how `-m` is implemented), which terminates the parsing of options and runs the following argument as literal Python code, and
- Support for the special script name `-`, which prompts `kernprof` to read from `stdin`.
It is implemented by a minor refactoring, which writes the received code …
=> ENH: auto-profile `stdin` or literal snippets

tests/test_line_profiler.py
Continuation of #341 (https://github.com/pyutils/line_profiler/pull/341#issuecomment-2887835055).
I did not add pytools as a requirement because the linecache support has not been merged there yet. The test here mimics that support.
=> test that generated code displays source code in profile

CHANGELOG.rst, line_profiler/_line_profiler.pyx, line_profiler/line_profiler.py, line_profiler/line_profiler.pyi, line_profiler/profiler_mixin.py, tests/test_line_profiler.py
Motivation
----
Currently, trying to use multiple `LineProfiler` instances just doesn't work, particularly if they are meant to be active simultaneously and to profile the same functions:
- In Python 3.12+, each instance will attempt to acquire/release the `'line_profiler'` soft-lock on `sys.monitoring` in its `.enable()`/`.disable()` methods. This causes a clash and an error due to a double `sys.monitoring.use_tool_id()`.
- In older Python version, the code will not error out, but only one profiler will see the line events and gather any actual profiling data since the C-level trace callback (`line_profiler/_line_profiler.pyx::python_trace_callback()`) only supports one profiler object. This will be alleviated by #334 where we can chain trace callbacks, but even then the feature is …
=> ENH: use multiple profiler instances

kernprof.py, tests/test_kernprof.py
Changes
----
- `kernprof.py`
- `_gather_preimport_targets()`:  
Fixed typo (`diagnostics.log.warn` -> `diagnostics.log.warning`)
- `_format_call_message()`:
- Added handling for `functools.partial`
- Added fallback handling for arbitrary callable
- `tests/test_kernprof.py`
- `test_bad_prof_mod_target()`:  
New test triggering the warning in `_gather_preimport_targets()`
- `test_call_with_diagnostics()`:  
New test for the various forms in which `_call_with_diagnostics()` is used
=> FIX: debug-mode and logging bugs in #337

CHANGELOG.rst, docs/source/auto/line_profiler.unset_trace.rst, line_profiler/CMakeLists.txt, line_profiler/_line_profiler.pyx, line_profiler/line_profiler.py, line_profiler/profiler_mixin.py, line_profiler/profiler_mixin.pyi, line_profiler/unset_trace.c, line_profiler/unset_trace.h, setup.py, tests/cython_example/cython_example.pyx, tests/cython_example/pyproject.toml, tests/cython_example/setup.py, tests/test_cython.py, tests/test_line_profiler.py
(May close #200. Related: cython/cython#3929, cython/cython#5140)
Synopsis
----
This PR fixes line-profiling for Cython code (which has been broken since the 4.0 version bump) by using an alternative source for code hashes with Cython functions. To that effect, we also switch to using `sys.monitoring` callbacks instead of the "legacy" tracing system where available (Python 3.12+), making it possible to line-profile Cython code in Python 3.13+.[^1]
Motivations
----
- It bugged me that we've made all these advancements in `line_profiler` and yet the `cython` folks were forced to [pin the version to 3](https://github.com/cython/cython/pull/5140), and it seemed like there are no good reasons that we shouldn't be able to support that with minimal overhead.
- Since Python 3.12 the existing …
=> FIX: restore Cython compatibility + pivot to `sys.monitoring`

line_profiler/_line_profiler.pyx, tests/test_line_profiler.py
The bug(s)
----
The behaviors of `LineProfiler.c_last_time` and `LineProfiler.last_time` are inconsistent:
```python
import line_profiler
prof = line_profiler.LineProfiler()
...
@prof
def func():
return prof.c_last_time.copy(), prof.last_time.copy()
assert not prof.c_last_time  # This may give a `KeyError` if no profiling was done on the thread
assert not prof.last_time
clt, lt = func()
assert not prof.c_last_time
assert not prof.last_time
assert clt
assert lt  # This assertion fails, `.last_time` empty despite `c_last_time` being not
assert set(clt) == {hash(f.__wrapped__.__code__.co_code)}
assert set(lt) == {f.__wrapped__.__code__}
```
The causes
----
Both `.c_last_time` and `.last_time` directly access the underlying `._c_last_time` with the key `threading.get_ident()`. However, it is …
=> FIX: `LineProfiler.last_time` always empty (and sometimes errors out)

CHANGELOG.rst, line_profiler/_line_profiler.pyx, tests/test_line_profiler.py
Closes #348.
Code changes
----
- `line_profiler/_line_profiler.pyx::LineProfiler.get_stats()`:  
Refactored to aggregate profiling data for duplicate (but distinct) code objects, which have separate entries in `.c_code_map` and `.code_hash_map` but is hashed to the same key by `label()` in the output `LineStats` object
Test changes
----
- `tests/test_line_profiler.py::test_duplicate_code_objects()`:  
New test that the bug described in the issue is fixed
=> FIX: aggregating profiling data from duplicate code objects

line_profiler/_line_profiler.pyx, tests/test_line_profiler.py
(Closes #355.)
Changes
----
- `line_profiler/_line_profiler.pyx`  
Added handling for `sys.monitoring.events.RAISE` and `.RERAISE`
- `tests/test_line_profiler.py::test_profiling_exception()`  
New test for checking whether `raise` statements and `finally: ...`
bodies are properly profiled
Caveats
----
- The new test X-Fails in Python 3.9 because exit data is missing for the `finally` body in a `try: ... except: ... finally: ...` block where the exception is re-raised (see e.g. [action `#1005`](https://github.com/pyutils/line_profiler/actions/runs/16326762849/job/46118806758)). The exact reason for the failure is unclear, but I suspect it has to do with python/cpython#83295.
=> FIX: missing line events for `raise` statements and `finally: ...` bodies in Python 3.12+

CHANGELOG.rst, docs/source/auto/line_profiler._line_profiler.rst, docs/source/conf.py, line_profiler/CMakeLists.txt, line_profiler/Python_wrapper.h, line_profiler/_diagnostics.py, line_profiler/_line_profiler.pyx, line_profiler/c_trace_callbacks.c, line_profiler/c_trace_callbacks.h, setup.py, tests/test_line_profiler.py, tests/test_sys_monitoring.py, tests/test_sys_trace.py
(Closes #333.)
Summary
----
(**Update 12 Jul**: this summary has been completely rewritten to reflect the latest state of affairs)
This draft PR adds C(-ython) level support to:
- Cache the existing trace-callback state(s) when `.enable()`-ing line profiling and restoring said state(s) when `.disable()`-ing it
- Optionally call the cached callback(s) from within the profiler callback(s)
- Improve compatibility with code (e.g. `doctest.DocTestRunner.run()`) using this Python-level paradigm to temporarily alter "legacy" tracing:
```python
callback = sys.gettrace()
try:
...  # Do something which involves swapping/unsetting the trace function
finally:
sys.settrace(callback)  # Restore the trace function
```
The option to switch back to using the "legacy" system in Python 3.12+ is also added …
=> Restore trace callback when the profiler is disabled

tests/test_cli.py, tests/test_complex_case.py
Replaced use of `tempfile.mkdtemp()` with the `tempfile.TemporaryDirectory()` context manager in the following tests:
- `tests/test_cli.py::test_cli()`
- `tests/test_complex_case.py::test_varied_complex_invocations()`
This removes the 12 tempdirs that erroneously persist after each `pytest` run.
=> FIX: tempdir-leaking tests

line_profiler/autoprofile/line_profiler_utils.pyi, line_profiler/cli_utils.py, line_profiler/cli_utils.pyi, line_profiler/line_profiler.pyi, line_profiler/profiler_mixin.pyi, line_profiler/scoping_policy.pyi, line_profiler/toml_config.py, line_profiler/toml_config.pyi
This PR addresses the following issues with recent PRs. (Note that there is no actual behavior change on the code-side).
- `line_profiler.cli_utils.add_argument(ArgumentParser(...), ...)` actually fails type check. 
- The stubs for the following types are botched:
- `line_profiler.toml_config.ConfigSource` should have a `.path` field instead of a `.source` field.
- `line_profiler.scoping_policy.ScopingPolicy` is missing an `.EXACT` item.
These typing bugs went under our nose because we only do stubs, and thus `mypy` don't really look into how we're using any of these. But `mypy` flared up the moment I installed the `line_profiler` in  a non-editable way in another project, which got me investigating... and here we are. This PR remedies the above bugs.
While we're at it, I also updated the …
=> FIX: stubs and `ConfigSource` doc

CHANGELOG.rst, line_profiler/_line_profiler.pyx, tests/test_line_profiler.py, tests/test_sys_monitoring.py
Closes #371 (maybe? see Caveats).
Code changes
---
- `line_profiler/_line_profiler.pyx`:  
Added `Py_XDECREF()` calls to temp objects used in the bodies of `_SysMonitoringState.call_callback()` and `legacy_trace_callback()`
Test changes
---
- `tests/test_line_profiler.py`:  
Updated the following tests to test that no ref counts leak for code objects:
- `test_double_decoration()`
- `test_function_decorator()`
- `test_gen_decorator()`
- `test_coroutine_decorator()`
- `test_async_gen_decorator()`
- `tests/test_sys_monitoring.py`:  
Updated `test_wrapping_trace()` to test that no ref counts leak for the return value of `sys.monitoring` tracebacks
Caveats
---
One of the subtests in `tests/test_line_profiler.py::test_async_gen_decorator()` is XFAIL-ed in Python 3.12+;
unlike the other 4 …
=> FIX: ref-count leaks

.github/workflows/tests.yml, build_wheels.sh, docs/source/conf.py, line_profiler/_line_profiler.pyx, pyproject.toml, requirements/build.txt, setup.py, tests/test_sys_monitoring.py
Attempt to enable 3.14 in the CI.
=> Update ci for 314

CHANGELOG.rst, MANIFEST.in, build_wheels.sh, clean.sh, line_profiler/_line_profiler.pyx, line_profiler/_map_helpers.pxd, setup.py
The following PR transforms this callback to this. More yellow is worse.
Before:
After:
The final result is to lower the worst-case overhead from ~60x to ~40x, which gets closer to the ~25-30x measured in 4.1.3. The average overhead remains at ~2x. Worst-case overhead output below:
```
kernprof -lvz test.py
Time Elapsed without profiling: 90.72ms
Time Elapsed profiling: 3686.82ms
Slowdown from profiling: 3596.1000000000004ms, 40.64x
Wrote profile results to 'test.py.lprof'
Timer unit: 1e-06 s
Total time: 2.78653 s
File: test.py
Function: main at line 3
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
3                                           def main(profiled=False):
4         1          2.9      2.9      0.0 …
```
=> Speed Up Worst-Case Overhead

.readthedocs.yml, CHANGELOG.rst, docs/source/conf.py, requirements/docs.txt
Closes #292.
This PR implements the proposed fixes in the issue, attempting to fix the search function in the docs based on readthedocs/sphinx_rtd_theme#1448 and the associated thread:
- `docs/source/cont.py`:  
`sphinxcontrib.jquery` is added as a Sphinx extension so there is a search to fall back on; this also allows for searches to work on local doc builds.
- `requirements/docs.txt`:  
Bumped `sphinx_rtd_theme` to a version (1.2.1) containing the linked PR fixing the issue.
- `.readthedocs.yml`:  
Bumped the build environment (Docker image and Python version) to something reasonably new but not bleeding-edge.
=> FIX: doc-searching

.readthedocs.yml, requirements/docs.txt
Right now [the online docs for `line_profiler.ipython_extension` are empty](https://kernprof.readthedocs.io/en/latest/auto/line_profiler.ipython_extension.html), probably because IPython is not installed in the build environment and thus said module is unavailable at build time. Considering the recent efforts on improving said module (#383) and inquiries thereon (#382), it makes sense for its docs to at least be publicly accessible.
Hence, this PR updates ~~`.readthedocs.yml`~~ **`requirements/docs.txt`** so that ReadTheDocs build the doc pages with IPython installed, and `autodocs` can thus (presumably and hopefully) build the page for the aforementioned submodule.
=> FIX: Installing IPython when building RTD docs
